### ISSUE TITLE
When a bad query is made (Example: Tom Cryz), appropriate error is not displayed

### ISSUE THREAD

**Issue by charanravi-online** [charanravi-online/Terminal-Wiki#1]
When a bad query is made like below, error should be something like "This seems to be an invalid topic."
![image](https://user-images.githubusercontent.com/84191978/233790400-f48450b2-3705-4ed0-abda-55ecff278fc0.png)
If we're able to print the error message displayed on the wikipedia page, even that would be great!

the errro page according to the query is: https://en.wikipedia.org/wiki/Tom_cryz
in this page, the error text is not parsed properly. 
![image](https://user-images.githubusercontent.com/84191978/233790653-7fa70664-ddb8-499e-921c-6738e5fca50d.png)

**Comment by amirbigg** [comment]
Hi
i fixed this problem and created a PR.

**Comment by charanravi-online** [comment]
Simple, yet effective!
Thanks @amirbigg
